name:                abstract-syntax
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ttuegel/abstract-syntax#readme
license:             BSD3
author:              Thomas Tuegel
maintainer:          ttuegel@mailbox.org
copyright:           2018 Thomas Tuegel
category:            Language

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - bound
  - deriving-compat
  - lens
  - recursion-schemes

default-extensions:
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleInstances
  - LambdaCase
  - RankNTypes
  - TypeFamilies

executables:
  syntax:
    source-dirs:      src
    main:             Main.hs
